"""empty message

Revision ID: 9faaa15a0680
Revises: 
Create Date: 2021-02-21 21:56:16.772198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9faaa15a0680'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_model',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('expiration_access_range', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('expiration_date', sa.DateTime(), nullable=False),
    sa.Column('password', sa.String(length=1024), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('password_model')
    # ### end Alembic commands ###
